-- MySQL Script generated by MySQL Workbench
-- Fri Feb 25 13:40:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Agency_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Agency_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Agency_db` DEFAULT CHARACTER SET utf8 ;
USE `Agency_db` ;

-- -----------------------------------------------------
-- Table `Agency_db`.`hotels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`hotels` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`hotels` (
  `id_hotel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_hotel`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_hotel_UNIQUE` ON `Agency_db`.`hotels` (`id_hotel` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `Agency_db`.`hotels` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`rooms` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`rooms` (
  `id_room` INT NOT NULL AUTO_INCREMENT,
  `room_type` VARCHAR(45) NOT NULL,
  `price_per_night` DECIMAL(7,2) NOT NULL,
  `hotel_FK` INT NOT NULL,
  PRIMARY KEY (`id_room`),
  CONSTRAINT `FK_hotel_rooms`
    FOREIGN KEY (`hotel_FK`)
    REFERENCES `Agency_db`.`hotels` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_room_UNIQUE` ON `Agency_db`.`rooms` (`id_room` ASC) VISIBLE;

CREATE INDEX `FK_hotel_rooms_idx` ON `Agency_db`.`rooms` (`hotel_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`bookings` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`bookings` (
  `id_booking` INT NOT NULL AUTO_INCREMENT,
  `date_from` DATE NOT NULL,
  `date_to` DATE NOT NULL,
  `room_FK` INT NOT NULL,
  `booking_costumer_FK` INT NOT NULL,
  PRIMARY KEY (`id_booking`),
  CONSTRAINT `FK_booking_rooms`
    FOREIGN KEY (`room_FK`)
    REFERENCES `Agency_db`.`rooms` (`id_room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_booking_UNIQUE` ON `Agency_db`.`bookings` (`id_booking` ASC) VISIBLE;

CREATE INDEX `FK_booking_rooms_idx` ON `Agency_db`.`bookings` (`room_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`flights` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`flights` (
  `id_flight` INT NOT NULL AUTO_INCREMENT,
  `flight_number` VARCHAR(45) NOT NULL,
  `origin` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `date_from` DATE NOT NULL,
  `date_to` DATE NOT NULL,
  PRIMARY KEY (`id_flight`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_flight_UNIQUE` ON `Agency_db`.`flights` (`id_flight` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`classes` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`classes` (
  `id_class` INT NOT NULL AUTO_INCREMENT,
  `seat_type` VARCHAR(45) NOT NULL,
  `available_seats` INT NOT NULL,
  `price_per_person` DECIMAL(7,2) NOT NULL,
  `flight_FK` INT NOT NULL,
  PRIMARY KEY (`id_class`),
  CONSTRAINT `FK_flight_classes`
    FOREIGN KEY (`flight_FK`)
    REFERENCES `Agency_db`.`flights` (`id_flight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_class_UNIQUE` ON `Agency_db`.`classes` (`id_class` ASC) VISIBLE;

CREATE UNIQUE INDEX `price_per_person_UNIQUE` ON `Agency_db`.`classes` (`price_per_person` ASC) VISIBLE;

CREATE INDEX `FK_flight_classes_idx` ON `Agency_db`.`classes` (`flight_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`customers` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`customers` (
  `id_costumer` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_costumer`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_costumer_UNIQUE` ON `Agency_db`.`customers` (`id_costumer` ASC) VISIBLE;

CREATE UNIQUE INDEX `user_name_UNIQUE` ON `Agency_db`.`customers` (`user_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`reservations` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`reservations` (
  `id_reservation` INT NOT NULL AUTO_INCREMENT,
  `class_FK` INT NOT NULL,
  `customer_FK` INT NOT NULL,
  PRIMARY KEY (`id_reservation`),
  CONSTRAINT `FK_class_reservations`
    FOREIGN KEY (`class_FK`)
    REFERENCES `Agency_db`.`classes` (`id_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_customer_reservations`
    FOREIGN KEY (`customer_FK`)
    REFERENCES `Agency_db`.`customers` (`id_costumer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_reservation_UNIQUE` ON `Agency_db`.`reservations` (`id_reservation` ASC) VISIBLE;

CREATE INDEX `FK_class_reservations_idx` ON `Agency_db`.`reservations` (`class_FK` ASC) VISIBLE;

CREATE INDEX `FK_customer_reservations_idx` ON `Agency_db`.`reservations` (`customer_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`people` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`people` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `email` NVARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_person_UNIQUE` ON `Agency_db`.`people` (`id_person` ASC) VISIBLE;

CREATE UNIQUE INDEX `dni_UNIQUE` ON `Agency_db`.`people` (`dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`booking_people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`booking_people` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`booking_people` (
  `idBookingPeople` INT NOT NULL,
  `id_booking` INT NOT NULL,
  `id_person` INT NOT NULL,
  PRIMARY KEY (`idBookingPeople`),
  CONSTRAINT `FK_bookingpeople_booking`
    FOREIGN KEY (`id_booking`)
    REFERENCES `Agency_db`.`bookings` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_bookingpeople_people`
    FOREIGN KEY (`id_person`)
    REFERENCES `Agency_db`.`people` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_bookingpeople_booking_idx` ON `Agency_db`.`booking_people` (`id_booking` ASC) VISIBLE;

CREATE INDEX `FK_bookingpeople_people_idx` ON `Agency_db`.`booking_people` (`id_person` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`booking_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`booking_customer` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`booking_customer` (
  `id_booking_customer` INT NOT NULL,
  `id_booking` INT NOT NULL,
  `id_customer` INT NOT NULL,
  PRIMARY KEY (`id_booking_customer`),
  CONSTRAINT `FK_bookingcustomer_booking`
    FOREIGN KEY (`id_booking`)
    REFERENCES `Agency_db`.`bookings` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_bookingcustomer_customer`
    FOREIGN KEY (`id_customer`)
    REFERENCES `Agency_db`.`customers` (`id_costumer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_booking_customer_idx` ON `Agency_db`.`booking_customer` (`id_booking` ASC) VISIBLE;

CREATE INDEX `FK_bookingcustomer_customer_idx` ON `Agency_db`.`booking_customer` (`id_customer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`reservation_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`reservation_customer` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`reservation_customer` (
  `id_reservation_customer` INT NOT NULL AUTO_INCREMENT,
  `id_reservation` INT NOT NULL,
  `id_customer` INT NOT NULL,
  PRIMARY KEY (`id_reservation_customer`),
  CONSTRAINT `FK_reservationcustomer_customer`
    FOREIGN KEY (`id_customer`)
    REFERENCES `Agency_db`.`customers` (`id_costumer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_reservationcustomer_reservation`
    FOREIGN KEY (`id_reservation`)
    REFERENCES `Agency_db`.`reservations` (`id_reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_reservation_customer_UNIQUE` ON `Agency_db`.`reservation_customer` (`id_reservation_customer` ASC) VISIBLE;

CREATE INDEX `FK_reservation_customer_idx` ON `Agency_db`.`reservation_customer` (`id_customer` ASC) VISIBLE;

CREATE INDEX `FK_reservationcustomer_reservation_idx` ON `Agency_db`.`reservation_customer` (`id_reservation` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`reservation_people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`reservation_people` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`reservation_people` (
  `id_reservation_people` INT NOT NULL AUTO_INCREMENT,
  `id_reservation` INT NOT NULL,
  `id_person` INT NOT NULL,
  PRIMARY KEY (`id_reservation_people`),
  CONSTRAINT `FK_reservationpeople_reservation`
    FOREIGN KEY (`id_reservation`)
    REFERENCES `Agency_db`.`reservations` (`id_reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_reservationpeople_people`
    FOREIGN KEY (`id_person`)
    REFERENCES `Agency_db`.`people` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idreservation_people_UNIQUE` ON `Agency_db`.`reservation_people` (`id_reservation_people` ASC) VISIBLE;

CREATE INDEX `FK_reservationpeople_reservation_idx` ON `Agency_db`.`reservation_people` (`id_reservation` ASC) VISIBLE;

CREATE INDEX `FK_reservationpeople_people_idx` ON `Agency_db`.`reservation_people` (`id_person` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`payment_methods` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`payment_methods` (
  `id_payment_method` INT NOT NULL AUTO_INCREMENT,
  `method` VARCHAR(45) NULL,
  PRIMARY KEY (`id_payment_method`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idpayment_method_UNIQUE` ON `Agency_db`.`payment_methods` (`id_payment_method` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
