-- MySQL Script generated by MySQL Workbench
-- Thu Mar  3 11:17:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Agency_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Agency_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Agency_db` DEFAULT CHARACTER SET utf8 ;
USE `Agency_db` ;

-- -----------------------------------------------------
-- Table `Agency_db`.`hotels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`hotels` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`hotels` (
  `id_hotel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `room_type` VARCHAR(45) NOT NULL,
  `price_per_night` DECIMAL(7,2) NOT NULL,
  `date_from` DATE NOT NULL,
  `date_to` DATE NOT NULL,
  `reserved` BIT NOT NULL,
  PRIMARY KEY (`id_hotel`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_hotel_UNIQUE` ON `Agency_db`.`hotels` (`id_hotel` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `Agency_db`.`hotels` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`bookings` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`bookings` (
  `id_booking` INT NOT NULL AUTO_INCREMENT,
  `hotel_FK` INT NOT NULL,
  `creation_date` DATE NOT NULL,
  `date_from` DATE NOT NULL,
  `date_to` DATE NOT NULL,
  `decimal` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id_booking`),
  CONSTRAINT `FK_bookings_hotels`
    FOREIGN KEY (`hotel_FK`)
    REFERENCES `Agency_db`.`hotels` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_bookings_hotels_idx` ON `Agency_db`.`bookings` (`hotel_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`flights` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`flights` (
  `id_flight` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `origin` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `seat_type` VARCHAR(80) NULL,
  `price_per_person` DECIMAL(7,2) NOT NULL,
  `date_from` DATE NOT NULL,
  `date_to` DATE NOT NULL,
  PRIMARY KEY (`id_flight`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agency_db`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`reservations` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`reservations` (
  `id_reservation` INT NOT NULL AUTO_INCREMENT,
  `flight_FK` INT NOT NULL,
  `creation_date` DATE NULL,
  `total` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id_reservation`),
  CONSTRAINT `FK_reservations_flights`
    FOREIGN KEY (`flight_FK`)
    REFERENCES `Agency_db`.`flights` (`id_flight`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `FK_reservations_flights_idx` ON `Agency_db`.`reservations` (`flight_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`customers` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`customers` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `user_name_UNIQUE` ON `Agency_db`.`customers` (`user_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`people` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`people` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `email` NVARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `dni_UNIQUE` ON `Agency_db`.`people` (`dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`booking_people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`booking_people` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`booking_people` (
  `id_booking_people` INT NOT NULL AUTO_INCREMENT,
  `booking_FK` INT NOT NULL,
  `person_FK` INT NOT NULL,
  PRIMARY KEY (`id_booking_people`),
  CONSTRAINT `FK_bookingpeople_booking`
    FOREIGN KEY (`booking_FK`)
    REFERENCES `Agency_db`.`bookings` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_bookingpeople_people`
    FOREIGN KEY (`person_FK`)
    REFERENCES `Agency_db`.`people` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_bookingpeople_booking_idx` ON `Agency_db`.`booking_people` (`booking_FK` ASC) VISIBLE;

CREATE INDEX `FK_bookingpeople_people_idx` ON `Agency_db`.`booking_people` (`person_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`book_res_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`book_res_customer` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`book_res_customer` (
  `id_book_res_customer` INT NOT NULL AUTO_INCREMENT,
  `customer_FK` INT NOT NULL,
  `booking_FK` INT NULL,
  `reservation_FK` INT NULL,
  `data_create` DATE NULL,
  `data_edit` DATE NULL,
  PRIMARY KEY (`id_book_res_customer`),
  CONSTRAINT `FK_book_res_customer_booking`
    FOREIGN KEY (`booking_FK`)
    REFERENCES `Agency_db`.`bookings` (`id_booking`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_book_res_customer_customer`
    FOREIGN KEY (`customer_FK`)
    REFERENCES `Agency_db`.`customers` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_book_res_customer_reservation`
    FOREIGN KEY (`reservation_FK`)
    REFERENCES `Agency_db`.`reservations` (`id_reservation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `FK_booking_customer_idx` ON `Agency_db`.`book_res_customer` (`booking_FK` ASC) VISIBLE;

CREATE INDEX `FK_bookingcustomer_customer_idx` ON `Agency_db`.`book_res_customer` (`customer_FK` ASC) VISIBLE;

CREATE INDEX `FK_bookingcustomer_reservation_idx` ON `Agency_db`.`book_res_customer` (`reservation_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`reservation_people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`reservation_people` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`reservation_people` (
  `id_reservation_people` INT NOT NULL AUTO_INCREMENT,
  `reservation_FK` INT NOT NULL,
  `person_FK` INT NOT NULL,
  PRIMARY KEY (`id_reservation_people`),
  CONSTRAINT `FK_reservationpeople_reservation`
    FOREIGN KEY (`reservation_FK`)
    REFERENCES `Agency_db`.`reservations` (`id_reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_reservationpeople_people`
    FOREIGN KEY (`person_FK`)
    REFERENCES `Agency_db`.`people` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_reservationpeople_reservation_idx` ON `Agency_db`.`reservation_people` (`reservation_FK` ASC) VISIBLE;

CREATE INDEX `FK_reservationpeople_people_idx` ON `Agency_db`.`reservation_people` (`person_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`tourist_pack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`tourist_pack` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`tourist_pack` (
  `id_tourist_pack` INT NOT NULL AUTO_INCREMENT,
  `creation_date` DATE NOT NULL,
  `customer_FK` INT NOT NULL,
  PRIMARY KEY (`id_tourist_pack`),
  CONSTRAINT `FK_tourist_pack_customer`
    FOREIGN KEY (`customer_FK`)
    REFERENCES `Agency_db`.`customers` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_tourist_pack_customer_idx` ON `Agency_db`.`tourist_pack` (`customer_FK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Agency_db`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agency_db`.`payments` ;

CREATE TABLE IF NOT EXISTS `Agency_db`.`payments` (
  `id_payment` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(70) NOT NULL,
  `number` VARCHAR(70) NOT NULL,
  `dues` INT NOT NULL,
  `booking_FK` INT NOT NULL,
  `reservation_FK` INT NOT NULL,
  PRIMARY KEY (`id_payment`),
  CONSTRAINT `FK_payments_bookings`
    FOREIGN KEY (`booking_FK`)
    REFERENCES `Agency_db`.`bookings` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_payments_reservations`
    FOREIGN KEY (`reservation_FK`)
    REFERENCES `Agency_db`.`reservations` (`id_reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_payments_bookings_idx` ON `Agency_db`.`payments` (`booking_FK` ASC) VISIBLE;

CREATE INDEX `FK_payments_reservations_idx` ON `Agency_db`.`payments` (`reservation_FK` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
