CREATE TABLE hotels(
  id_hotel VARCHAR(8) PRIMARY KEY,
  name VARCHAR(18) NOT NULL UNIQUE,
  location VARCHAR(14) NOT NULL,
  room_type VARCHAR(8) NOT NULL,
  price_per_night INTEGER NOT NULL,
  date_from DATE NOT NULL,
  date_to DATE NOT NULL,
  reserved BIT NOT NULL
);

CREATE TABLE flights(
  id_flight BIGINT AUTO_INCREMENT PRIMARY KEY,
  flight_number VARCHAR(10) NOT NULL,
  origin VARCHAR(14) NOT NULL,
  destination VARCHAR(14) NOT NULL,
  seat_type VARCHAR(8) NOT NULL,
  price_per_person FLOAT NOT NULL,
  date_from DATE NOT NULL,
  date_to DATE NOT NULL
);

--CREATE TABLE RESERVATION(
--  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
--  ROOM_ID BIGINT NOT NULL,
--  GUEST_ID BIGINT NOT NULL,
--  RES_DATE DATE
--);
--
--ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
--ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
--CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
