CREATE TABLE HOTEL(
  HOTEL_CODE VARCHAR(8) PRIMARY KEY,
  NAME VARCHAR(18) NOT NULL UNIQUE,
  LOCATION VARCHAR(14) NOT NULL,
  ROOM_TYPE VARCHAR(8) NOT NULL,
  PRICE_PER_NIGHT INTEGER NOT NULL,
  DATE_FROM DATE NOT NULL,
  DATE_TO DATE NOT NULL,
  RESERVED BIT NOT NULL
);

CREATE TABLE FLIGHT(
  FLIGHT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FLIGHT_NUMBER VARCHAR(10) NOT NULL,
  ORIGIN VARCHAR(14) NOT NULL,
  DESTINATION VARCHAR(14) NOT NULL,
  SEAT_TYPE VARCHAR(8) NOT NULL,
  PRICE_PER_PERSON FLOAT NOT NULL,
  DATE_FROM DATE NOT NULL,
  DATE_TO DATE NOT NULL
);

--CREATE TABLE RESERVATION(
--  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
--  ROOM_ID BIGINT NOT NULL,
--  GUEST_ID BIGINT NOT NULL,
--  RES_DATE DATE
--);
--
--ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
--ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
--CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
